[package]
publish = false
name = "reinhardt-params"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Parameter extraction system for Reinhardt, inspired by FastAPI"

[dependencies]
reinhardt-http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
serde_urlencoded = "0.7"
form_urlencoded = "1.2"
http = "1.0"
urlencoding = "2.1"
regex = { workspace = true }
validator = { version = "0.20.0", features = ["derive"], optional = true }
multer = { version = "3.1", optional = true }
futures-util = { version = "0.3", optional = true }
uuid = { workspace = true, optional = true }
reinhardt-core = {workspace = true, features = ["validators"], optional = true}

[features]
default = ["multi-value-arrays", "uuid"]
validation = ["reinhardt-validators", "validator"]
multi-value-arrays = []
multipart = ["multer", "futures-util"]
uuid = ["dep:uuid"]
full = ["validation", "multi-value-arrays", "multipart", "uuid"]

[dev-dependencies]
tokio = { workspace = true }
bytes = { workspace = true }
hyper = { workspace = true }
