[package]
name = "reinhardt-forms-macros"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Procedural macros for reinhardt-forms"
repository.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
reinhardt-forms-macros-ast = { workspace = true }
syn = { workspace = true, features = ["full", "parsing", "extra-traits"] }
proc-macro2 = { workspace = true }
quote = { workspace = true }

[dev-dependencies]
trybuild = { workspace = true }
rstest = { workspace = true }
proptest = { workspace = true }
