[build]
target = "index.html"
public-url = "/"
dist = "dist"
filehash = false

[watch]
watch = ["src/", "index.html"]

[serve]
addresses = ["127.0.0.1"]
port = 8080
open = false
aliases = []  # Disable automatic hostname detection

[clean]
cargo = true
