[package]
name = "backends"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
sqlx = { workspace = true, features = ["chrono"] }
async-trait = { workspace = true }
chrono = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }

[features]
default = ["postgres"]
postgres = []
mysql = []
sqlite = []
all-databases = ["postgres", "mysql", "sqlite"]
