[package]
name = "reinhardt-serializers"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
reinhardt-apps = { workspace = true }
reinhardt-parsers = { path = "../parsers" }
reinhardt-renderers = { workspace = true }
reinhardt-negotiation = { path = "../negotiation" }
reinhardt-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
urlencoding = "2.1"
chrono = { workspace = true }
sqlx = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
