[package]
name = "renderers-ext"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
reinhardt-renderers = { workspace = true }
reinhardt-exception = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
